version: '3'

services:
  backend:
    container_name: bfc-backend
    build:
      context: .
    depends_on:
      - db
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    ports:
      - "1337:1337"
    restart: on-failure
    volumes:
      - ./backend:/srv/app

  db:
    container_name: bfc-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - /home/albert/Escriptori/BFC-postgres-volume:/var/lib/postgresql/data
    restart: unless-stopped