# fly.toml file generated for bfc-backend on 2023-04-05T01:35:07+02:00

app = "bfc-backend"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "mad"

[build]
  dockerfile = "Dockerfile.prod"

[deploy]
  strategy = "rolling"

[[services]]
  protocol = "tcp"
  internal_port = 1337
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "1m0s"
    timeout = "10s"
    grace_period = "1m0s"
    restart_limit = 10
